#!/usr/bin/env python3
"""Generate ``.grant.yaml`` from vendored supply-chain thresholds or env.

Allow-list resolution order:

1. ``LICENSE_ALLOW_LIST`` env (JSON array string) when non-empty and not ``[]``
2. ``license_allow_list`` from ``THRESHOLDS_PATH`` (default:
   ``scripts/supply-chain.profile.thresholds.yml``)

Writes a grant policy with ``require-license: false`` so an empty org deny list
still allows meaningful permissive OSS via the allow list. File-search is left
disabled by the caller via ``grant check --disable-file-search``.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path


DEFAULT_THRESHOLDS = 'scripts/supply-chain.profile.thresholds.yml'
DEFAULT_OUT = '.grant.yaml'


def _parse_allow_list(raw: str) -> list[str]:
    """Return non-empty string patterns from a JSON array string."""
    data = json.loads(raw)
    if not isinstance(data, list):
        raise ValueError('LICENSE_ALLOW_LIST must be a JSON array')
    out: list[str] = []
    for x in data:
        if isinstance(x, str):
            s = x.strip()
            if s:
                out.append(s)
    return out


def _allow_from_thresholds(path: Path) -> list[str]:
    """Parse ``license_allow_list`` block from a simple YAML thresholds file."""
    if not path.is_file():
        raise FileNotFoundError(str(path))

    text = path.read_text(encoding='utf-8', errors='replace')
    # Inline JSON array form
    m = re.search(r'^license_allow_list:\s*(\[[^\]]*\])\s*(?:#.*)?$', text, flags=re.M)
    if m:
        return _parse_allow_list(m.group(1))

    # Block list form:
    # license_allow_list:
    #   - "MIT"
    #   - Apache-*
    m = re.search(r'^license_allow_list:\s*(?:#.*)?$', text, flags=re.M)
    if not m:
        raise ValueError(f'license_allow_list key missing in {path}')

    patterns: list[str] = []
    for line in text[m.end() :].splitlines():
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if re.match(r'^[A-Za-z0-9_]+:', line):
            break
        item = re.match(r'^\s*-\s*(.+?)\s*$', line)
        if not item:
            break
        val = item.group(1).strip()
        if (val.startswith('"') and val.endswith('"')) or (
            val.startswith("'") and val.endswith("'")
        ):
            val = val[1:-1]
        if val:
            patterns.append(val)

    if not patterns:
        raise ValueError(f'license_allow_list is empty in {path}')
    return patterns


def _resolve_allow_list() -> tuple[list[str], str]:
    """Return (patterns, source description). Fail closed on missing thresholds."""
    raw = os.environ.get('LICENSE_ALLOW_LIST', '').strip()
    if raw and raw != '[]':
        return _parse_allow_list(raw), 'LICENSE_ALLOW_LIST env'

    thr = Path(os.environ.get('THRESHOLDS_PATH', DEFAULT_THRESHOLDS))
    return _allow_from_thresholds(thr), f'thresholds file {thr}'


def _render_grant_yaml(allow: list[str]) -> str:
    """Render a minimal grant config (allow-list, require-license false)."""
    lines = [
        '# Generated by scripts/generate_grant_config.py — do not edit by hand.',
        '# File-search disabled at CLI: grant check --disable-file-search',
        'allow:',
    ]
    for pat in allow:
        # Quote when needed for YAML safety
        if any(c in pat for c in ':#{}[]&*!|>\'"%@`') or pat != pat.strip():
            lines.append(f'  - {json.dumps(pat)}')
        else:
            lines.append(f'  - {pat}')
    lines.extend(
        [
            # Org license_deny_list is empty; do not fail packages with no license metadata.
            'require-license: false',
            'require-known-license: false',
            '',
        ]
    )
    return '\n'.join(lines)


def main() -> int:
    """Write ``.grant.yaml`` (or ``GRANT_CONFIG_PATH``) from thresholds / env."""
    out = Path(os.environ.get('GRANT_CONFIG_PATH', DEFAULT_OUT))
    thr = Path(os.environ.get('THRESHOLDS_PATH', DEFAULT_THRESHOLDS))
    try:
        allow, src = _resolve_allow_list()
    except FileNotFoundError:
        print(
            f'error: thresholds file missing at {thr} and LICENSE_ALLOW_LIST is empty; '
            'failing closed (SC-LIC-001).',
            file=sys.stderr,
        )
        return 2
    except (json.JSONDecodeError, ValueError) as e:
        print(f'Invalid license allow list / thresholds: {e}', file=sys.stderr)
        return 2

    print(f'generate_grant_config: effective allow list ({src}): {json.dumps(allow)}')
    out.write_text(_render_grant_yaml(allow), encoding='utf-8')
    print(f'Wrote {out}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())  # pragma: no cover
